### ISSUE TITLE
There is an erorr when i roslaunch orb_object_slam mono.launch

### ISSUE THREAD

**Issue by SharineLee** [shichaoy/cube_slam#12]
Hello shichaoy,

Thanks for your sharing,

There is an erorr when i roslaunch orb_object_slam mono.launch

[ros_mono-3] process has died [pid 6899, exit code -11, cmd /home/sharine/cubeslam_ws/devel/lib/orb_object_slam/ros_mono /home/sharine/cubeslam_ws/src/cube_slam/orb_object_slam/Vocabulary/ORBvoc.bin /home/sharine/cubeslam_ws/src/cube_slam/orb_object_slam/Examples/Monocular/KITTI04-12_me.yaml /camera/image_raw:=/kitti/left/image_raw __name:=ros_mono __log:=/home/sharine/.ros/log/8b3d30fe-efc8-11e9-a14c-9cb6d0e0ac2d/ros_mono-3.log].
log file: /home/sharine/.ros/log/8b3d30fe-efc8-11e9-a14c-9cb6d0e0ac2d/ros_mono-3*.log

**Comment by shichaoy** [comment]
hi @SharineLee sorry for late reply but I couldn't infer anything from your output. Is it compiling error or runtime? can you see the executable?
