### ISSUE TITLE
In tracking.cc, does the function AssociateCuboids also compute cuboid scale?

### ISSUE THREAD

**Issue by drscopus** [shichaoy/cube_slam#17]
See the following code:
https://github.com/shichaoy/cube_slam/blob/23304a9c25dc33d9ec16cdfbb2494800ec7dcda0/orb_object_slam/src/Tracking.cc#L1948

How does the value “1.9420, 0.8143, 0.7631” come? Thanks!

**Comment by shichaoy** [comment]
that's the car dimensions.  [length, width, height] /2

**Comment by drscopus** [comment]
Can this dimension value be computed by the visual measurement or other methods? Not by manually setting. Thanks!
