### ISSUE TITLE
How to run the mono_dynamic.launch successfully?

### ISSUE THREAD

**Issue by drscopus** [shichaoy/cube_slam#18]
We want to learn how you deal with dynamic objects by reading related codes in your great work. But now we can not run mono_dynamic.launch successfully. Could you give us more instructions and  provide some data like seq07(including the txt files) to run it successfully? Thanks!~

**Comment by drscopus** [comment]
@shichaoy hi, could you give any instructions on how to run mono_dynamic.launch? Any instruction is appreciated.  Thanks.

**Comment by drscopus** [comment]
@shichaoy Would you like to share the mask image mentioned in the code of Frame.cc for removing dynamic features.
 `       std::string pred_mask_img_name = base_data_folder + "/rcnn_labelmap_3dmatched/" + frame_index_c + "_maskmap.png";`

**Comment by shichaoy** [comment]
hi for dynamic slam data, see here https://drive.google.com/open?id=1T2PmK3Xt5Bq9Z7UhV8FythvramqhOo0a

**Comment by drscopus** [comment]
Thank you very much!
