### ISSUE TITLE
liborb_object_slam.so (not found)

### ISSUE THREAD

**Issue by chwongAI** [shichaoy/cube_slam#19]
During the make step, around 94%, I got this error:

No rule to make target '/home/ros/cubeslam_ws/src/cube_slam/orb_object_slam/Thirdparty/DBoW2/lib/libDBoW2.so', needed by '/home/ros/cubeslam_ws/devel/lib/liborb_object_slam.so'.  Stop.

I've went into the folder "cubeslam_ws/devel/lib/", and "liborb_object_slam.so" is missing. 

Im on Ubuntu16.04
![image](https://user-images.githubusercontent.com/56913202/70017764-f2d16480-15be-11ea-8207-ceb940262d08.png)

**Comment by shichaoy** [comment]
Hi @chwongAI  I have updated ```install_dependenices.sh```
