### ISSUE TITLE
Would you like to share the code of your DSO paper?

### ISSUE THREAD

**Issue by drscopus** [shichaoy/cube_slam#28]
Hi, @shichaoy Shichao,  Would you like to share the code of  your paper:
Direct Monocular Odometry Using Points and Lines
Shichao Yang, Sebastian Scherer, IEEE/Intl. Conf. on Robotics and Automation, ICRA, 2017, Oral

https://shichaoy.github.io/Publications/icra_2017_line.pdf

Thanks!

**Comment by shichaoy** [comment]
you can refer to this https://drive.google.com/open?id=1n6vfOxlUm4y0TGNHiTXF52sTJFg-ZR9e
it's ros package based on LSD slam. Haven't run it for long time.

**Comment by drscopus** [comment]
Many thanks! Got the link and downloaded the code.
