### ISSUE TITLE
How to run it with my own image sequences

### ISSUE THREAD

**Issue by FatEvilCat** [shichaoy/cube_slam#4]
Hi shichaoy,
Thanks for your sharing. I have some question on how to run it on my own image sequences.
In notes,I supposed that the filter_2d_obj_txts, raw_imgs, detect_cuboids_saved.txt, pop_cam_poses_saved.txt are required. The filter_2d_obj_txts,detect_cuboids_saved.txt may obtain using other packages. So can you give more details on how to get pop_cam_poses_saved.txt?
Thanks in advance.

**Comment by shichaoy** [comment]
hi, pop_cam_poses is the camera poses to ground (as mentioned in readme, roll/pitch/height is useful).   In current code of toy datasets (without orbslam to provide pose), you can just use a fixed camera pose parallel to ground, the single image ```cube_detection ``` (https://github.com/shichaoy/cube_slam/blob/master/detect_3d_cuboid/include/detect_3d_cuboid/detect_3d_cuboid.h) can sample and estimate camera roll/pitch, but may not be accurate.     In the future, we will upload code integrated with orb slam, then this pose can be directly provided by SLAM estimation.

**Comment by zhangjun-xyz** [comment]
@shichaoy Do you have any specific plans on publish your code integrated orb slam?

**Comment by shichaoy** [comment]
@zhangjun-xyz  forget to mention, already integrated into orb slam.
