### ISSUE TITLE
Weights for different costs in the optimization

### ISSUE THREAD

**Issue by moshanATucsd** [shichaoy/cube_slam#5]
Hi, thanks for the code! It says in the paper `From our
experiments, object-camera and point-camera measurements
have similar weights`, I am wondering where are those weights? I found this in the code, is this the weight? 

```
		Vector9d inv_sigma;inv_sigma<<1,1,1,1,1,1,1,1,1;
		inv_sigma = inv_sigma*2.0*cube_landmark_meas->meas_quality;
		Matrix9d info = inv_sigma.cwiseProduct(inv_sigma).asDiagonal();
```

**Comment by shichaoy** [comment]
hi thanks for the interest. yes, parameter 2 can be tuned, but is in the same magnitude from our tests.

**Comment by moshanATucsd** [comment]
I am wondering what's the magnitude, 0.01, 0.1, 1 etc?

**Comment by shichaoy** [comment]
From my experience, usually between 1-5.

**Comment by moshanATucsd** [comment]
Got it!
