### ISSUE TITLE
Test on Own The Images

### ISSUE THREAD

**Issue by godblezzme29** [shichaoy/cube_slam#9]
Hello I have some question related to the cube_slam
1.In your example of object_slam_example.launch, you have detect_cuboids_saved.txt, pop_cam_poses_saved.txt, and truth_cam_poses.txt. May I know how you generate this file? Because I would like to test it with my own images
Thank you

**Comment by shichaoy** [comment]
hi I have a section in Readme talking about this. https://github.com/shichaoy/cube_slam#notes

**Comment by yipingp** [comment]
> hi I have a section in Readme talking about this. https://github.com/shichaoy/cube_slam#notes

Hi, how do you collect truth_cam_poses? The first frame of it seems to be the transformation to the ground coord, and important to 3d cuboid detection? How should I get pose relative to ground?
